# Generated by Django 6.0.4 on 2026-04-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_conversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationparticipant',
            name='left_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
